services:
  marketplace-auth-api:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: marketplace-auth-api
    container_name: marketplace-auth-api
    volumes:
      - /home/kinoko/logs/marketplace-auth-api:/logs
    #      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33301:33301"

networks:
  backend:
    external: true
